version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/go/src/github.com/ShunyaNagashige/imgconv
    ports:
      #APIサーバ用のポート
      - ${APP_PORT}:8080